service: mdstream-backend
org: itcmedia

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}

  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: false

  # ======== 環境変数の読み込み方針 ========
  # 1) .env.{stage} or system env
  # 2) CI/CD パイプラインであれば、GitHub Actions (もしくは他のサービス) の secrets を
  #    process.env.* として注入する
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}     # S3バケット名 (ローカルなら .env.dev など、CI/CD は secrets)
    S3_PREFIX: ${self:custom.prefixes.${self:provider.stage}}
    ALLOWED_REFERER: ${env:ALLOWED_REFERER}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}"
        - "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*"

functions:
  getMarkdownList:
    handler: dist/handler.getMarkdownList
    events:
      - httpApi:
          path: /markdown/list
          method: get

  getMarkdownDetail:
    handler: dist/handler.getMarkdownDetail
    events:
      - httpApi:
          path: /markdown/{slug}
          method: get

plugins:
  - serverless-offline

custom:
  # デプロイ時に .env.{stage} を読み込み (ローカルのみ)
  # CI/CD では通常 secrets を環境変数に注入することで対応
  dotenv:
    path: .env.${self:provider.stage}

  prefixes:
    dev: dev/
    prod: prod/
